config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'index' => 'translate#index'
  post 'get_translate' => 'translate#translator'

  root to: 'translate#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include TranslateHelper
end

app/controllers/translate_controller.rb
class TranslateController < ApplicationController
  
  def index
  end

  def translator
    if request.xhr?
      token = getToken
      data = getTranslate(token, params[:str])
    end
    Slack.chat_postMessage(text: 'Translation: ' + data, username: 'translator_bot', channel: "#general")
    render json: {eng: data}.to_json, status: 200
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/translate_helper.rb
require 'rexml/document'

module TranslateHelper
  def getTranslate(token = nil, text="")
    token = getToken if token.nil?
    
    response = RestClient.get 'https://api.microsofttranslator.com/v2/http.svc/Translate',
      {
        params: {
          appid: 'Bearer' + ' ' + token,
          text: text,
          to: 'en' 
        },
        'Accept' => 'application/xml'
      }
  
  REXML::Document.new(response.body).elements['string'].text
end

private

def getToken
  response = RestClient.post 'https://api.cognitive.microsoft.com/sts/v1.0/issueToken',
    {},
    {
      'Ocp-Apim-Subscription-Key' => Rails.application.secrets.translator_key,
      'Accept' => 'application/jwt'
    }
    response.body
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MicrosoftTranslator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/translate/index.html.erb
<div class="loading">
  <%= image_tag(asset_path('loading.gif'), alt: 'Loading') %>
</div>
<div class="loading-overlay"></div>

<h1>翻訳</h1>

<textarea name="str" id="str" cols="30" rows="10"></textarea>
<%= link_to '翻訳', get_translate_path, id: 'get_translate', method: :post, remote: true %>
<textarea name="result" id="result" cols="30" rows="10" readonly></textarea>